### ISSUE TITLE
The meaning of l_type

### ISSUE THREAD

**Issue by KangHuaLi** [anantzoid/BEGAN-pytorch#1]
Very thanks for your code sharing.
Recently, I trace for your code.
But a slight point I didn't realize.
In [here](https://github.com/anantzoid/BEGAN-pytorch/blob/master/main.py#L43), you define a parameter which called `l_type`.
What does it mean?
The criterion is `L1loss`  is define in [here](https://github.com/anantzoid/BEGAN-pytorch/blob/master/main.py#L73),
Next, you split as two situation in [here](https://github.com/anantzoid/BEGAN-pytorch/blob/master/main.py#L139).
However, `L1loss` is the same as `torch.mean(torch.abs(<diff>))`.

**Comment by anantzoid** [comment]
Thanks for pointing this out.
As far as I remember, when I was performing experiments, I tested with L1 and L2 losses, and must have probably changed criterion to L1 as well later on.
So currently, choosing l_type to be anything shouldn't make a difference as both the losses are same.
